services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $disableCreation: "%pw.pushword_template_editor.disable_creation%"
      $canBeEditedList: "%pw.pushword_template_editor.can_be_edited_list%"

  Pushword\TemplateEditor\ElementAdmin:
    tags: ['controller.service_arguments']
